#!/bin/bash
#
# Startup script for Flume-Repose
#
### BEGIN INIT INFO
# Provides: flume-ng
# Required-Start: $network
# Required-Stop:  $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short Description: Startup script for flume-ng
# Description: Script for starting Flume as a daemon on system startup
### END INIT INFO

set -e

# Source function library.
. /lib/lsb/init-functions

# Set sensible defaults
LOG_PATH=/var/log/flume
# NOTE:  flume references java from JAVA_HOME, so this is configured differently than the repose
# init script.
export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64
CONFIG_DIRECTORY=/opt/flume/conf
COMMAND=/opt/flume/bin/flume-ng
USER=flume
NAME=flume-ng
DAEMON_HOME=/opt/flume
PID_FILE=/var/run/${NAME}.pid
START_ARGS="--start --quiet --oknodo --make-pidfile --pidfile ${PID_FILE} --background"
RUN_ARGS="agent -n repose-agent -c $CONFIG_DIRECTORY -f $CONFIG_DIRECTORY/cf-flume-conf.properties"
# NOTE:  flume declares its JVM arguments in /opt/flume/conf/flume-env.sh, not here

# Can override the defaults in /etc/sysconfig
. /etc/sysconfig/flume-ng

if [ ! -d $DAEMON_HOME ]; then
  echo "Unable to find $NAME's directory: $DEAMON_HOME."
  exit 1
fi

if [ ! -d $CONFIG_DIRECTORY ]; then
  echo "Unable to find $CONFIG_DIRECTORY."
  exit 1
fi

if [ ! -d $LOG_PATH ]; then
  echo "Unable to log to $LOG_PATH."
  exit 1
fi

start()
{
  start-stop-daemon $START_ARGS --chuid $USER:$USER --exec $COMMAND -- $RUN_ARGS
  log_progress_msg "Started"
}

stop()
{
  start-stop-daemon -p $PID_FILE --stop --user $USER --retry 5 --exec $COMMAND
  log_progress_msg "Stopped"
}


case "$1" in
  start)
    log_daemon_msg "Starting $NAME"
    start
    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping $NAME"
    stop
    log_end_msg 0
    ;;

  restart)
    log_daemon_msg "Restarting $NAME"
    stop
    start
    log_end_msg 0
    ;;

  status)
    status_of_proc -p $PID_FILE $COMMAND $NAME && exit 0 || exit $?
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
esac
