#!/bin/bash
#
# Startup script for Flume-Repose
#
# chkconfig: 345 85 15     - start or stop process definition within the boot process
# description: Script for starting Flume as a daemon on system startup
# processname: flume-ng

# Source function library.
. /etc/rc.d/init.d/functions

# Set sensible defaults
LOG_PATH=/var/log/flume
# NOTE:  flume references java from JAVA_HOME, so this is configured differently than the repose
# init script.
export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64
CONFIG_DIRECTORY=/opt/flume/conf
COMMAND=/opt/flume/bin/flume-ng
USER=flume
NAME=flume-ng
DAEMON_HOME=/opt/flume
PID_FILE=/var/run/${NAME}.pid
START_ARGS="-c $DAEMON_HOME -p $PID_FILE -u $USER -o $LOG_PATH/stdout.log -e $LOG_PATH/stderr.log -l /var/lock/subsys/$NAME"
RUN_ARGS="agent -n repose-agent -c $CONFIG_DIRECTORY -f $CONFIG_DIRECTORY/cf-flume-conf.properties"
# NOTE:  flume declares its JVM arguments in /opt/flume/conf/flume-env.sh, not here
daemonize=/usr/sbin/daemonize

# Can override the defaults in /etc/sysconfig
. /etc/sysconfig/flume-ng

if [ ! -d $DAEMON_HOME ]; then
  echo "Unable to find $NAME's directory: $DEAMON_HOME."
  exit 1
fi

if [ ! -d $CONFIG_DIRECTORY ]; then
  echo "Unable to find $CONFIG_DIRECTORY."
  exit 1
fi

if [ ! -d $LOG_PATH ]; then
  echo "Unable to log to $LOG_PATH."
  exit 1
fi

start()
{
  echo -n "Starting $NAME: "
  daemon $daemonize $START_ARGS $COMMAND $RUN_ARGS 
  echo
}

stop()
{
  echo -n "Stopping $NAME: "

  killproc -p $PID_FILE -d 3 $NAME && rm -f /var/lock/subsys/$NAME
  echo
}


case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  status)
    status -p $PID_FILE $NAME
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
esac
